const APPLICATION_PORT = parseInt(process.env.APPLICATION_PORT);
const JSON_WEB_TOKEN = {
	SECRET_KEY: process.env.JWT_SECRET_KEY,
	PATH_PRIVATE_KEY: process.env.JWT_PATH_PRIVATE_KEY,
	ALGORITHM: process.env.JWT_ALGORITHM,
	TTL: parseInt(process.env.JWT_TTL)
};

const HTTP_STATUS_CODE = {
	UNAUTHORIZATION: 401,
	BAD_REQUEST: 400
}
module.exports = {
	APPLICATION_PORT: APPLICATION_PORT,
	JSON_WEB_TOKEN: JSON_WEB_TOKEN,
	HTTP_STATUS_CODE: HTTP_STATUS_CODE
};